version: '3'
# chmod 777 redis/redis.log
# chmod 777 redis/data
# chmod 777 mysql/data
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    restart: always
    container_name: redis    
